<?php
require("db-config/security.php");
require_once('../vendor/tecnickcom/tcpdf/tcpdf.php');

// Redirect if not logged in
if (!isLoggedIn()) {
    header('Location: index');
    exit;
}

$student_id = $_SESSION['user_id'];

// Get student information with teacher details
$student_query = "
    SELECT 
        s.*,
        sec.section_name,
        t.firstname as teacher_firstname,
        t.lastname as teacher_lastname,
        t.mi as teacher_mi
    FROM students s
    LEFT JOIN sections sec ON s.section_id = sec.id
    LEFT JOIN teachers t ON sec.teacher_id = t.id
    WHERE s.id = ?
";

$stmt = $pdo->prepare($student_query);
$stmt->execute([$student_id]);
$student = $stmt->fetch(PDO::FETCH_ASSOC);

// Get all journals ordered from oldest to newest
$journals_query = "
    SELECT 
        id,
        journal_date,
        title,
        reflection,
        mood,
        location,
        created_at
    FROM student_journals 
    WHERE student_id = ?
    ORDER BY journal_date ASC, created_at ASC
";

$stmt = $pdo->prepare($journals_query);
$stmt->execute([$student_id]);
$journals = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Get images for each journal
foreach ($journals as $key => $journal) {
    $images_query = "
        SELECT 
            image_path
        FROM journal_images 
        WHERE journal_id = ?
        ORDER BY sort_order ASC
    ";
    
    $stmt = $pdo->prepare($images_query);
    $stmt->execute([$journal['id']]);
    $images = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    $journals[$key]['images'] = $images;
}

// Calculate stats
$total_photos = 0;
foreach ($journals as $journal) {
    $total_photos += count($journal['images']);
}

// Mood counts
$mood_counts = [
    'happy' => 0,
    'excited' => 0,
    'neutral' => 0,
    'tired' => 0,
    'stressed' => 0
];

foreach ($journals as $journal) {
    if (isset($mood_counts[$journal['mood']])) {
        $mood_counts[$journal['mood']]++;
    }
}

// Create PDF document
class PDF extends TCPDF {
    // Page header
    public function Header() {
        // Only show header on pages after cover
        if ($this->getPage() > 1) {
            $this->SetFont('helvetica', 'B', 9);
            $this->SetTextColor(102, 126, 234);
            $this->Cell(0, 10, 'IMMERSION E-JOURNAL', 0, false, 'L', 0, '', 0, false, 'M', 'M');
            
            $this->SetFont('helvetica', 'I', 8);
            $this->SetTextColor(150, 150, 150);
            $this->Cell(0, 10, 'Page '.$this->getAliasNumPage(), 0, false, 'R', 0, '', 0, false, 'M', 'M');
            $this->Ln(8);
            
            // Line separator
            $this->SetDrawColor(102, 126, 234);
            $this->SetLineWidth(0.3);
            $this->Line(15, $this->GetY(), 195, $this->GetY());
            $this->Ln(5);
        }
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        
        // Line separator
        $this->SetDrawColor(200, 200, 200);
        $this->SetLineWidth(0.2);
        $this->Line(15, $this->GetY(), 195, $this->GetY());
        $this->Ln(2);
        
        // Copyright or footer text
        $this->SetFont('helvetica', 'I', 7);
        $this->SetTextColor(150, 150, 150);
        // $this->Cell(0, 5, 'Generated by Immersion System', 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// Create new PDF document
$pdf = new PDF('P', 'mm', 'A4', true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Immersion System');
$pdf->SetAuthor(htmlspecialchars($student['firstname'] . ' ' . $student['lastname']));
$pdf->SetTitle('E-Journal - ' . htmlspecialchars($student['firstname'] . ' ' . $student['lastname']));

// Remove default header/footer
$pdf->setPrintHeader(true);
$pdf->setPrintFooter(true);

// Set margins
$pdf->SetMargins(20, 30, 20);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(15);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 25);

// Add first page (cover)
$pdf->AddPage();

// ===== COVER PAGE =====
// Set cover background (light gradient effect)
$pdf->SetFillColor(248, 250, 252);
$pdf->Rect(0, 0, 210, 297, 'F');

// Decorative elements
$pdf->SetDrawColor(102, 126, 234);
$pdf->SetLineWidth(2);
$pdf->Line(20, 40, 190, 40);
$pdf->Line(20, 257, 190, 257);

// Main title
$pdf->SetY(70);
$pdf->SetFont('helvetica', 'B', 36);
$pdf->SetTextColor(102, 126, 234);
$pdf->Cell(0, 20, 'E-JOURNAL', 0, 1, 'C');
$pdf->Ln(5);

// Student name
$pdf->SetFont('helvetica', 'B', 24);
$pdf->SetTextColor(44, 62, 80);
$pdf->Cell(0, 15, htmlspecialchars(strtoupper($student['lastname']) . ', ' . $student['firstname']), 0, 1, 'C');
$pdf->Ln(5);

// Student details box
$pdf->SetFillColor(240, 244, 248);
$pdf->SetTextColor(60, 60, 60);
$pdf->SetFont('helvetica', '', 12);
$pdf->SetX(50);
$pdf->Cell(110, 40, '', 0, 1, 'C', true);

$pdf->SetY($pdf->GetY() - 35);
$pdf->SetX(50);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(110, 8, 'Student Information', 0, 1, 'C');
$pdf->SetX(50);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(110, 7, 'Section: ' . htmlspecialchars($student['section_name'] ?? 'Not Assigned'), 0, 1, 'C');
$pdf->SetX(50);
$pdf->Cell(110, 7, 'Teacher: ' . htmlspecialchars($student['teacher_firstname'] . ' ' . $student['teacher_lastname'] ?? 'Not Assigned'), 0, 1, 'C');
$pdf->SetX(50);
$pdf->Cell(110, 7, 'LRN: ' . htmlspecialchars($student['lrn'] ?? 'N/A'), 0, 1, 'C');

$pdf->Ln(10);

// Stats in boxes
$pdf->SetY(180);
$pdf->SetFillColor(102, 126, 234);
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 14);

// // First row of stats
// $pdf->SetX(30);
// $pdf->Cell(40, 25, count($journals), 0, 0, 'C', true);
// $pdf->SetX(85);
// $pdf->Cell(40, 25, $total_photos, 0, 0, 'C', true);
// $pdf->SetX(140);
// $pdf->Cell(40, 25, count($journals) > 0 ? $journals[count($journals)-1]['journal_date'] : 'N/A', 0, 1, 'C', true);

// $pdf->SetY(205);
// $pdf->SetFont('helvetica', '', 10);
// $pdf->SetTextColor(100, 100, 100);
// $pdf->SetX(30);
// $pdf->Cell(40, 8, 'Total Journals', 0, 0, 'C');
// $pdf->SetX(85);
// $pdf->Cell(40, 8, 'Total Photos', 0, 0, 'C');
// $pdf->SetX(140);
// $pdf->Cell(40, 8, 'Latest Entry', 0, 1, 'C');

// // Second row of stats (moods)
// $pdf->SetY(230);
// $pdf->SetFillColor(102, 126, 234, 20);
// $pdf->SetTextColor(60, 60, 60);
// $pdf->SetFont('helvetica', 'B', 10);

// $pdf->SetX(30);
// $pdf->Cell(40, 20, $mood_counts['happy'], 1, 0, 'C', true);
// $pdf->SetX(85);
// $pdf->Cell(40, 20, $mood_counts['excited'], 1, 0, 'C', true);
// $pdf->SetX(140);
// $pdf->Cell(40, 20, $mood_counts['tired'] + $mood_counts['stressed'], 1, 1, 'C', true);

// $pdf->SetY(250);
// $pdf->SetFont('helvetica', '', 9);
// $pdf->SetX(30);
// $pdf->Cell(40, 6, 'Happy Days', 0, 0, 'C');
// $pdf->SetX(85);
// $pdf->Cell(40, 6, 'Excited Days', 0, 0, 'C');
// $pdf->SetX(140);
// $pdf->Cell(40, 6, 'Challenging Days', 0, 1, 'C');

// Generation date at bottom
// $pdf->SetY(270);
// $pdf->SetFont('helvetica', 'I', 9);
// $pdf->SetTextColor(150, 150, 150);
// $pdf->Cell(0, 6, 'Generated on: ' . date('F d, Y'), 0, 1, 'C');

// ===== JOURNAL ENTRIES =====
foreach ($journals as $index => $journal) {
    // Add new page for each journal
    $pdf->AddPage();
    
    // Journal header with decorative elements
    $pdf->SetFillColor(245, 247, 250);
$pdf->Rect(15, $pdf->GetY(), 180, 25, 'F');

    
    // Journal number
    $pdf->SetY($pdf->GetY() + 5);
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetTextColor(102, 126, 234);
    $pdf->Cell(0, 8, 'Entry #' . ($index + 1), 0, 1, 'R');
    
    // Date
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->SetTextColor(80, 80, 80);
    $pdf->Cell(0, 6, date('F d, Y', strtotime($journal['journal_date'])), 0, 1, 'L');
    
    // Title
    $pdf->SetFont('helvetica', 'B', 22);
    $pdf->SetTextColor(44, 62, 80);
    $pdf->MultiCell(0, 12, htmlspecialchars($journal['title']), 0, 'L', 0, 1);
    $pdf->Ln(2);
    
    // Mood and location badges
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(100, 100, 100);
    
    if ($journal['mood'] || $journal['location']) {
        $pdf->SetFillColor(240, 244, 248);
        
        if ($journal['mood']) {
            $pdf->SetX(20);
            $pdf->Cell(40, 8, ' Mood: ' . ucfirst($journal['mood']), 0, 0, 'L', true);
        }
        
        if ($journal['location']) {
            $pdf->SetX(70);
            $pdf->Cell(0, 8, ' Location: ' . htmlspecialchars($journal['location']), 0, 1, 'L', true);
        } else {
            $pdf->Ln(8);
        }
        $pdf->Ln(5);
    }
    
    // Reflection content with proper formatting
    $pdf->SetFont('helvetica', '', 11);
    $pdf->SetTextColor(40, 40, 40);
    
    // Split reflection into paragraphs
    $paragraphs = explode("\n\n", $journal['reflection']);
    foreach ($paragraphs as $paragraph) {
        if (trim($paragraph)) {
            $pdf->MultiCell(0, 6, htmlspecialchars(trim($paragraph)), 0, 'L', 0, 1);
            $pdf->Ln(3);
        }
    }
    
    // Images - UNIFORM SIZE
    if (!empty($journal['images'])) {
        $pdf->Ln(5);
        
        // Section title
        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->SetTextColor(102, 126, 234);
        $pdf->Cell(0, 8, 'Attached Images', 0, 1, 'L');
        $pdf->Ln(2);
        
        // Get current Y position
        $startY = $pdf->GetY();
        $imageCount = count($journal['images']);
        
        // UNIFORM IMAGE SIZE - All images same dimensions
        $imageWidth = 75;  // Fixed width
        $imageHeight = 60; // Fixed height - UNIFORM for all images!
        
        $imagesPerRow = 2;
        $spacing = 10;
        $startX = 25;
        
        for ($i = 0; $i < min($imageCount, 6); $i++) {
            $imagePath = $journal['images'][$i]['image_path'];
            
            if (file_exists($imagePath)) {
                // Calculate position
                $col = $i % $imagesPerRow;
                $row = floor($i / $imagesPerRow);
                
                $x = $startX + ($col * ($imageWidth + $spacing));
                $y = $startY + ($row * ($imageHeight + $spacing));
                
                // Add image with UNIFORM dimensions
                $pdf->Image($imagePath, $x, $y, $imageWidth, $imageHeight, '', '', '', false, 300, '', false, false, 0, 'CM', false, false);
                
                // Add border and caption
                $pdf->SetDrawColor(200, 200, 200);
                $pdf->Rect($x, $y, $imageWidth, $imageHeight);
                
                // Add image number
                $pdf->SetFont('helvetica', '', 8);
                $pdf->SetTextColor(150, 150, 150);
                $pdf->SetXY($x + $imageWidth - 15, $y + $imageHeight - 10);
                // $pdf->Cell(10, 5, '#' . ($i + 1), 0, 0, 'C');
            }
        }
        
        // Update Y position after images
        $rowsNeeded = ceil(min($imageCount, 6) / $imagesPerRow);
        $pdf->SetY($startY + ($rowsNeeded * ($imageHeight + $spacing)) + 5);
        
        // Note if there are more images
        if ($imageCount > 6) {
            $pdf->SetFont('helvetica', 'I', 9);
            $pdf->SetTextColor(150, 150, 150);
            $pdf->Cell(0, 6, '... and ' . ($imageCount - 6) . ' more photos', 0, 1, 'L');
            $pdf->Ln(2);
        }
    }
    
    // Add subtle separator at the end of each journal
    if ($index < count($journals) - 1) {
        $pdf->SetDrawColor(220, 220, 220);
        $pdf->SetLineWidth(0.2);
        $pdf->Line(20, $pdf->GetY() + 10, 190, $pdf->GetY() + 10);
    }
}

// Output PDF
$pdf->Output('E-Journal_' . $student['lastname'] . '_' . date('Y-m-d') . '.pdf', 'I');
exit;
?>