<?php
date_default_timezone_set('Asia/Manila');
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
function emailing($messageVar,$email){
#GENERATING EMAIL NOTIFICATION
                
                      require '../phpmailer/src/Exception.php';
                      require '../phpmailer/src/PHPMailer.php';
                      require '../phpmailer/src/SMTP.php';

                        $mail = new PHPMailer(true);
                         
                          $mail->isSMTP();
                          $mail->Host = "{$_ENV['SMTP_HOST']}"; // mail.madasikinara.com
                          $mail->SMTPAuth = true;
                          $mail->Username = "{$_ENV['SMTP_USERNAME']}"; //jlouisuru@gmail.com
                          $mail->Password = "{$_ENV['SMTP_PASSWORD']}"; //ttqm fhro jntr ozcx
                          $mail->SMTPSecure = "{$_ENV['SMTP_SECURE']}"; //ssl
                          $mail->Port = $_ENV['SMTP_PORT']; //465
                          $mail->setFrom("{$_ENV['SMTP_SETFROM']}", "{$_ENV['SMTP_SETFROM_HEADER']}"); //jlouisuru@gmail.com

                          $mail->addAddress($email); // ito ang recipient 
                        
                          #THIS IS FOR LOCAL VERSION

                        $mail->isHTML(true);

                        $mail->Subject = "Your DVMS Account has been created!";
                        $mail->Body = "
                        <h3>Your registration has been made at exactly (".date("d-M-Y H:i:s").").
                        </h3>
                        <p>$messageVar</p>
                        <br />
                        <hr />
                        <p>
                        This is an Automatic E-mail generated by the MSSC-DVMS Portal. <br /> Refrain from Replying. Thank you.
                        </p>
                        ";
                        if($mail->send()){  
                          return $data['message'] = '<p class="text text-success"> Password Sent </p>'; 
                           
                        }
                        else {
                          return $data['message'] = '<p class="text text-danger">Error 404: Please Contact your Developer.</p>';
                          
                        }

                #GENERATING EMAIL NOTIFICATION ENDDDD
  }
?>

<?php 
//tHIS IS for Online
// date_default_timezone_set('Asia/Manila');
// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;
// function emailing($messageVar,$email){
// #GENERATING EMAIL NOTIFICATION
                
//                       require '../phpmailer/src/Exception.php';
//                       require '../phpmailer/src/PHPMailer.php';
//                       require '../phpmailer/src/SMTP.php';
//                     //   require '../vendor/autoload.php';
//                      $mail = new PHPMailer(true);
//               try { 
//                         $mail->SMTPDebug = 1;
//                         $mail->isSMTP();
//                         $mail->Host       = 'mail.mssc-official.com'; // Outgoing SMTP server
//                         $mail->SMTPAuth   = true;                     // Enable SMTP authentication
//                         $mail->Username   = 'e-dvms@mssc-official.com'; // Your full email address same from setFrom()
//                         $mail->Password   = 'aLouIe@0@5';     // The email password you set in cPanel
//                         $mail->SMTPSecure = 'ssl'; // SSL since you’re using port 465
//                         $mail->Port       = 465;                      // Outgoing SMTP port
//                           $mail->setFrom("e-dvms@mssc-official.com", "E-DVMS"); //jlouisuru@gmail.com

//                           $mail->addAddress($email,'Recipient'); // ito ang recipient 
                        
//                           #THIS IS FOR LOCAL VERSION

//                         $mail->isHTML(true);

//                         $mail->Subject = "Your DVMS Account has been created!";
//                         $mail->Body = "
//                         <h3>Your registration has been made at exactly (".date("d-M-Y H:i:s").").
//                         </h3>
//                         <p>$messageVar</p>
//                         <br />
//                         <hr />
//                         <p>
//                         This is an Automatic E-mail generated by the MSSC-DVMS Portal. <br /> Refrain from Replying. Thank you.
//                         </p>
//                         ";
                        
                        
                       
//                             if($mail->send()){  
//                               return ' Password Sent'; 
                               
//                             }
//                             else {
//                               return 'Error 404: Please Contact your Developer.';
//                             }
                              
//                         } catch (Exception $e) {
//                         echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
// }

//                 #GENERATING EMAIL NOTIFICATION ENDDDD
//   }
?>
